default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  variables:
    intervalstyle: iso_8601

development:
  <<: *default
  database: parallel_tests_app_development

test: &test
  <<: *default
  database: parallel_tests_app_test

production:
  <<: *default
  database: parallel_tests_app_production
  username: parallel_tests_app
  password: <%= ENV['PARALLEL_TESTS_APP_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test
